### Questions 1:
##### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [11]:
import numpy as np
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

## Questions 2:
###### Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.


In [5]:
import numpy as np
lst1 = []
lst2 = []

for i in range(5):
    input1 = int(input())
    lst1.append(input1)

for i in range(5):
    input1 = int(input())
    lst2.append(input1)

print("List1 is :",lst1)
print("List2 is", lst2)
# conversion of List to Array

arr1 = np.array(lst1)
arr2 = np.array(lst2)
print("Lst1 converted into array  :", arr1)
print("List2 converted into array :", arr2)

# concatenation of arrays

array_concat = np.concatenate((arr1, arr2))

print("concatenation of arrays are :", array_concat)

# Sorting of array

print("Sorted array :", np.sort(array_concat))

2
4
5
5
4
4
6
5
8
3
List1 is : [2, 4, 5, 5, 4]
List2 is [4, 6, 5, 8, 3]
Lst1 converted into array  : [2 4 5 5 4]
List2 converted into array : [4 6 5 8 3]
concatenation of arrays are : [2 4 5 5 4 4 6 5 8 3]
Sorted array : [2 3 4 4 4 5 5 5 6 8]


## Questions 3:
##### Write a code snippet to find the dimensions of a ndarray and its size.


In [10]:
arr1=np.array([[1,2,3],[3,4,5]])
print("Dimension:- ",arr1.ndim)
print("size:- ",arr1.size)

Dimension:-  2
size:-  6


### Questions 4:
###### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims


In [18]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)
print(arr)

# np.newaxis:-  to add a new axis
arr2 = arr[np.newaxis, :]
print(arr2.shape)
print(arr2)

(6,)
[1 2 3 4 5 6]
(1, 6)
[[1 2 3 4 5 6]]


In [17]:
arr3 = np.expand_dims(a, axis=1)
print(arr.shape)
print(arr)

# np.expand_dims:-  expand an array by inserting a new axis at a specified position.
arr3 = np.expand_dims(arr, axis=0)
print(arr3.shape)
print(arr3)

(6,)
[1 2 3 4 5 6]
(1, 6)
[[1 2 3 4 5 6]]


### Questions 5:
###### Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()


In [15]:
import numpy as np
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2=np.array([["a","b","c"],["d","e","f"],["g","h","i"]])
print(np.vstack((arr1,arr2)))
print()
print(np.hstack((arr1,arr2)))

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']]

[['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']
 ['7' '8' '9' 'g' 'h' 'i']]


### Questions 6:
###### How to get unique items and counts of unique items?

In [16]:
arr = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(arr, return_counts=True)
count = np.asarray((unique, counts)).T

print(count)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
